ARG NODE_VERSION

FROM node:${NODE_VERSION}-alpine
RUN apk update

WORKDIR /app

RUN yarn global add turbo
COPY package.json ./package.json
COPY yarn.lock ./yarn.lock
COPY turbo.json ./turbo.json
COPY ./packages/eslint-config-custom/package.json ./packages/eslint-config-custom/package.json
COPY ./packages/tsconfig/package.json ./packages/tsconfig/package.json
COPY ./packages/ui/package.json ./packages/ui/package.json
COPY ./apps/web/package.json ./apps/web/package.json

RUN yarn install --network-timeout 6000000

COPY ./packages ./packages
COPY ./apps/web ./apps/web
RUN rm -rf ./apps/web/.env

EXPOSE 3000

ENV PORT 3000

CMD [ "yarn", "run", "dev", "--filter=web" ]
