version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NODE_VERSION=${NODE_VERSION:-16.14.2}
    container_name: web
    restart: always
    ports:
      - ${WEB_PORT:-3000}:3000
    env_file:
      - .env.development
